[metadata]
name = dblise
version = 0.1.0
author = Roman Valov
author_email = roman.valov@gmail.com
description = interact with redis database via dataclasses
url = https://github.com/chatio-ai/dblise
license =
classifiers =

[options]
install_requires = file: requirements.txt
package_dir =
    = src

[options.extras_require]
dev = file: requirements.dev.txt
